spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yupi?characterEncoding=utf8&useSSL=false
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080